[tool.poetry]
name = "trading-bots"
version = "0.1.0"
description = "Scan a DEX's hottest coin based on returns and volume."
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "trading_bots"}]

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.0.0"
requests = "^2.28.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
